module.exports = [
    {
        imagenCompañiaIda: "" ,
        horaSalidaIda: "" ,
        origenIda: "" ,
        fechaSalidaIda: "" ,
        tiempoIda: "" ,
        directoIda: "" ,
        horaLlegadaIda: "" ,
        destinoIda: "" ,
        fechaLlegadaIda: "" ,
        imagenCompañiaVuelta: "" ,
        horaSalidaVuelta: "" ,
        origenVuelta: "" ,
        fechaSalidaVuelta: "" ,
        tiempoVuelta: "" ,
        directoVuelta: "" ,
        horaLlegadaVuelta: "" ,
        destinoVuelta: "" ,
        fechaLlegadaVuelta: "" ,
        precio: "" ,
        producto: ""
    } ,
    {
        imagenCompañiaIda: "" ,
        horaSalidaIda: "" ,
        origenIda: "" ,
        fechaSalidaIda: "" ,
        tiempoIda: "" ,
        directoIda: "" ,
        horaLlegadaIda: "" ,
        destinoIda: "" ,
        fechaLlegadaIda: "" ,
        imagenCompañiaVuelta: "" ,
        horaSalidaVuelta: "" ,
        origenVuelta: "" ,
        fechaSalidaVuelta: "" ,
        tiempoVuelta: "" ,
        directoVuelta: "" ,
        horaLlegadaVuelta: "" ,
        destinoVuelta: "" ,
        fechaLlegadaVuelta: "" ,
        precio: "" ,
        producto: ""
    },
    {
        imagenCompañiaIda: "" ,
        horaSalidaIda: "" ,
        origenIda: "" ,
        fechaSalidaIda: "" ,
        tiempoIda: "" ,
        directoIda: "" ,
        horaLlegadaIda: "" ,
        destinoIda: "" ,
        fechaLlegadaIda: "" ,
        imagenCompañiaVuelta: "" ,
        horaSalidaVuelta: "" ,
        origenVuelta: "" ,
        fechaSalidaVuelta: "" ,
        tiempoVuelta: "" ,
        directoVuelta: "" ,
        horaLlegadaVuelta: "" ,
        destinoVuelta: "" ,
        fechaLlegadaVuelta: "" ,
        precio: "" ,
        producto: ""
    }
]